### ISSUE TITLE
The Aerogel does not produce Cherenkov Radiation.

### ISSUE THREAD

**Issue by anir92** [MustafaSchmidt/geant4-tutorial#1]
As done in Video-6 of the Youtube lecture series, I added the Aerogel material and specified additional parameters. I don't see any cherenkov radiation, and only a proton is passing as before. How to solve this, please let me know.

If any output print/ script files are required, please inform.

**Comment by giovixo** [comment]
I wrote up the example #6 here: https://github.com/giovixo/geant4-quick-start It works on my pc (mac OS geant4.10.07.p03 installation).

**Comment by Jazcess** [comment]
This is because the energy array needs to be in increasing order, so swap the values around that the tutorial says.

**Comment by LaaaaaaaaiFe** [comment]
> This is because the energy array needs to be in increasing order, so swap the values around that the tutorial says.

Thank you so much. I have checked my code over and over again.

**Comment by mr-tousif** [comment]
Can anyone help me :

CMake Error at /Applications/CMake.app/Contents/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB: Found unsuitable version "1.2.11", but required is at
  least "1.2.13" (found
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/lib/libz.tbd)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.25/Modules/FindZLIB.cmake:166 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /Applications/CMake.app/Contents/share/cmake-3.25/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /opt/homebrew/Caskroom/miniforge/base/lib/Geant4-11.0.3/Geant4Config.cmake:274 (find_dependency)
  B1/CMakeLists.txt:13 (find_package)

**Comment by ReemRad** [comment]
> This is because the energy array needs to be in increasing order, so swap the values around that the tutorial says.

Thank!. This is solved the problem.

**Comment by Puyandeh** [comment]
Greetings everyone,

I am using the latest version of Geant4 in 2025 (i.e., 4-11.3.2), I have tried to write the energies in increasing order but when I run the program, I see no Cerenkov radiation. It did not solve the problem. I have no idea what I should do. Also, a user suggested the following line right after defining the mptAerogel,
`
mptAerogel->AddProperty("RINDEX", energy, rindexAerogel, 2, true, true);`

But it does no work for me, I don't see any Cerenkov radiation.
